version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking SNS_TOPIC_ARN: ${SNS_TOPIC_ARN}"
      - if [ -z "${SNS_TOPIC_ARN}" ]; then echo "Error: SNS_TOPIC_ARN is not set!" && exit 1; fi
      - echo "Creating notification message file..."
      - echo "CODEBUILD_INITIATOR:${CODEBUILD_INITIATOR}" > sns-message.txt
      - echo "CODEBUILD_BUILD_ID:${CODEBUILD_BUILD_ID}" >> sns-message.txt
      - echo "CODEBUILD_SOURCE_REPO_URL:${CODEBUILD_SOURCE_REPO_URL}" >> sns-message.txt
      - echo "CODEBUILD_SOURCE_VERSION:${CODEBUILD_SOURCE_VERSION}" >> sns-message.txt
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION:${CODEBUILD_RESOLVED_SOURCE_VERSION}" >> sns-message.txt
      - echo "DOCKER_COMPOSE_VERSION:${DOCKER_COMPOSE_VERSION}" >> sns-message.txt
      - cat sns-message.txt
      - echo "Sending notification..."
      - aws sns publish --topic-arn "${SNS_TOPIC_ARN}" --subject "AWS CodeBuild Started - ${CODEBUILD_BUILD_ID}" --message file://sns-message.txt
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo "Pulling Docker Images for cache..."
      - docker-compose pull --ignore-pull-failures --parallel

  build:
    commands:
      - echo "Building the Docker image..."
      - docker-compose build

  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker-compose push
      - echo "Printing environment variables..."
      - printenv
      - echo "Sending build log..."
      - aws sns publish --topic-arn "${SNS_TOPIC_ARN}" --subject "AWS CodeBuild Log - ${CODEBUILD_BUILD_ID}" --message file://log.txt
      - echo "CODEBUILD_BUILD_SUCCEEDING:${CODEBUILD_BUILD_SUCCEEDING}" >> sns-message.txt
      - echo "Sending completion notification..."
      - aws sns publish --topic-arn "${SNS_TOPIC_ARN}" --subject "AWS CodeBuild Completed - ${CODEBUILD_BUILD_ID}" --message file://sns-message.txt
